// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cpclapp.Models;

#nullable disable

namespace cpclapp.Migrations
{
    [DbContext(typeof(ApidbContext))]
    [Migration("20240729171501_emp_lop")]
    partial class emp_lop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cpclapp.Models.Empview", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<string>("C02_Function_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C02_Function_Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C12_Positioncode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("H01_EMP_NUM")
                        .HasColumnType("int");

                    b.Property<string>("H01_First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("H01_birth_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("H01_join_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("P08_Payset_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employeeId");

                    b.ToTable("Empview");
                });

            modelBuilder.Entity("cpclapp.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("cpclapp.Models.Passtable", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("prno")
                        .HasColumnType("int");

                    b.HasKey("employeeId");

                    b.HasIndex("prno")
                        .IsUnique();

                    b.ToTable("Passtables");
                });

            modelBuilder.Entity("cpclapp.Models.cpcl_cant_daily_menu_items", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<DateTime>("CDATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("CQTY")
                        .HasColumnType("int");

                    b.Property<int>("ITEM_CODE")
                        .HasColumnType("int");

                    b.Property<string>("SUB_ITEM_CODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("act_rate")
                        .HasColumnType("real");

                    b.Property<string>("itemdesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subitemdesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sysid")
                        .HasColumnType("int");

                    b.HasKey("employeeId");

                    b.ToTable("cpcl_cant_daily_menu_items");
                });

            modelBuilder.Entity("cpclapp.Models.cpcl_emp_name_vw", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<int>("C02_Cost_Center_No")
                        .HasColumnType("int");

                    b.Property<string>("C02_Function_Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("H01_join_date")
                        .HasColumnType("date");

                    b.Property<string>("c02_function_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c03_organisation_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("c09_grade")
                        .HasColumnType("int");

                    b.Property<int>("h01_emp_num")
                        .HasColumnType("int");

                    b.Property<string>("h01_first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employeeId");

                    b.ToTable("cpcl_emp_name_vw");
                });

            modelBuilder.Entity("cpclapp.Models.cpcl_lop_day_wise", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<string>("company_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("days")
                        .HasColumnType("real");

                    b.Property<string>("flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("from_dt")
                        .HasColumnType("datetime2");

                    b.Property<string>("location_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("period")
                        .HasColumnType("int");

                    b.Property<int>("pr_no")
                        .HasColumnType("int");

                    b.Property<string>("time_stamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("to_dt")
                        .HasColumnType("datetime2");

                    b.HasKey("employeeId");

                    b.HasIndex("pr_no");

                    b.ToTable("cpcl_lop_day_wise");
                });

            modelBuilder.Entity("cpclapp.Models.cpcl_telephone", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<string>("DEPARTMENT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GRADE")
                        .HasColumnType("int");

                    b.Property<int>("Intercom_no")
                        .HasColumnType("int");

                    b.Property<long>("Mobile_no")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Modified_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("PT_Direct")
                        .HasColumnType("bigint");

                    b.Property<int>("PT_Extn")
                        .HasColumnType("int");

                    b.Property<string>("Residence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("prno")
                        .HasColumnType("int");

                    b.HasKey("employeeId");

                    b.HasIndex("prno")
                        .IsUnique();

                    b.ToTable("cpcl_Telephones");
                });

            modelBuilder.Entity("cpclapp.Models.Passtable", b =>
                {
                    b.HasOne("cpclapp.Models.Empview", null)
                        .WithMany()
                        .HasForeignKey("prno")
                        .HasPrincipalKey("H01_EMP_NUM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("cpclapp.Models.cpcl_lop_day_wise", b =>
                {
                    b.HasOne("cpclapp.Models.Empview", null)
                        .WithMany()
                        .HasForeignKey("pr_no")
                        .HasPrincipalKey("H01_EMP_NUM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("cpclapp.Models.cpcl_telephone", b =>
                {
                    b.HasOne("cpclapp.Models.Empview", "Empview")
                        .WithOne("Telephone")
                        .HasForeignKey("cpclapp.Models.cpcl_telephone", "prno")
                        .HasPrincipalKey("cpclapp.Models.Empview", "H01_EMP_NUM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empview");
                });

            modelBuilder.Entity("cpclapp.Models.Empview", b =>
                {
                    b.Navigation("Telephone")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
